name: slack-notification

on: 
  workflow_dispatch:
    inputs:
      message:
        description: 'Display events on slack'
        required: false
        default: 'Hello World!'
jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Notify Event
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: send-message
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: C02NC668LJV
          slack-function: send-message
          slack-text: Hello team!! A new "${{ github.event_name }}" has been triggered by "${{github.actor}}" in "${{ github.repository }}:${{github.ref}}" with sha ${{github.sha}}. See the progreess on https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Some step in between
        run: echo "..."
      - name: Test started
        uses: archive/github-actions-slack@master
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
          slack-text: Beginning with the tests rounds
          slack-optional-thread_ts: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
      - name: Test Passed
        uses: archive/github-actions-slack@master
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
          slack-text: ":large_green_circle: All Tests has been passed"
          slack-optional-thread_ts: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
      - name: Test FAILED
        uses: archive/github-actions-slack@master
        with:
          slack-function: send-message
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: ${{ fromJson(steps.send-message.outputs.slack-result).response.channel }}
          slack-text: ":red_circle: One or more tests has been failed"
          slack-optional-thread_ts: ${{ fromJson(steps.send-message.outputs.slack-result).response.message.ts }}
