# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      changeset-only:
        type: boolean
        description: Create changeset only
        required: true
        default: "true"
      account:
        type: choice
        description: testing the choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt2
env:
  opt1: 123
  opt2: 456
  opt3: 789
  deployer-opt1: ubuntu-latest
  deployer-opt2: ubuntu-18.04
  deployer-opt3: macos-latest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.MapRunners.outputs.runner }}
    steps:
      - name: Map Runners
        id: MapRunners
        run: echo "::set-output name=runner::${{env[format('deployer-{0}',github.event.inputs.account)]}}"

  job2:
    needs: job1
    # The type of runner that the job will run on
    runs-on: ${{needs.job1.outputs.runner}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      
      - name: Dumping selected variables
        run: |
          echo "Changeset: ${{github.event.inputs.changeset-only}}"
          echo "Account: ${{github.event.inputs.account}}"
          echo "That's all folks!"
      - name: The freaking test
        run: |
          echo "The choose is: ${{env[github.event.inputs.account]}}"
          echo "It will select ${{format('deployer-{0}',env[github.event.inputs.account])}}"
          echo "Weird thing: ${{env[format('deployer-{0}',env[github.event.inputs.account])]}}"

