# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      changeset-only:
        type: boolean
        description: Create changeset only
        required: true
        default: "true"
      account:
        type: choice
        description: testing the choice
        options:
          - opt1
          - opt2
          - opt3
        default: opt2
env:
  opt1: 123
  opt2: 456
  opt3: 789
  deployer-123: do1
  deployer-456: do2
  deployer-789: do3

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  step1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      
      - name: Dumping selected variables
        run: |
          echo "Changeset: ${{github.event.inputs.changeset-only}}"
          echo "Account: ${{github.event.inputs.account}}"
          echo "That's all folks!"
      - name: The freaking test
        run: |
          echo "The choose is: ${{env[github.event.inputs.account]}}"
          echo "It will select ${{join('deployer-',env[github.event.inputs.account])}}"
          echo "Weird thing: ${{env[join('deployer-',env[github.event.inputs.account]t)]}}"

